# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# MD004/ul-style
MD004: false
# MD012/no-multiple-blanks
MD012:
  # Two blank lines is nice above some headings
  maximum: 2
# MD013/line-length
MD013: false
# MD022/blanks-around-headings
MD022: false
# MD024/no-duplicate-heading
MD024:
  siblings_only: true
# MD026/no-trailing-punctuation
MD026:
  punctuation: ".,;:。，；："
# MD032/blanks-around-lists
MD032: false
# MD033/no-inline-html
MD033: false
# MD036/no-emphasis-as-heading
MD036: false
# MD041:first-line-heading/first-line-h1
MD041: false
# MD059/descriptive-link-text
MD059: false
